### PR TITLE
Add input for --fail-on-errors flag and update dependencies

### PR DESCRIPTION
**Pull request by szymonkozak**
In the #4 `--fail-on-errors=true` flag was introduced, but its value was hardcoded, this PR introduces this flag value as an input. (10c88be)

On this page:  https://discuss.bitrise.io/t/run-danger-v1-0-0/10316 there is a workaround:
> Set is_skippable: true on the step to revert the previous behavior. 

However `is_skippable` flag isn’t always good option, because when this step was failed from other reason than danger fail then `is_skippable: true` could hide the real problem, eg. missing/invalid github/gitlab api token.

Also updated dependencies.

### CODE REVIEW

**Review by koral-- — DISMISSED** [review]

**Comment by szymonkozak** [comment]
@godrei Could you look on this?

**Comment by lszucs** [comment]
Hi @szymonkozak

Thanks for the PR! Apologies for the delayed response. You're argument is completely valid. However, we'd require minor changes before we merge it.

- title: Fail on errors
- input key: fail_on_errors
- description: Marks the step as failed if Danger reports any issues
- value_options: please use the yaml list format for the options (e.g. as seen here: https://github.com/search?q=org%3Abitrise-steplib+value_options&type=Code)

**Review by lszucs — APPROVED** [review]
Thanks for the contribution! :) Will have this merged soon.

**Review by trapacska — APPROVED** [review]

**Comment by szymonkozak** [comment]
@lszucs @trapacska Thanks for merging, unfortunately this PR: https://github.com/bitrise-io/bitrise-steplib/pull/2359 was closed as requested by author. What's the reason of this action?

**Comment by lszucs** [comment]
Hi @szymonkozak,

Based on further discussions with the product team, it was decided to introduce some changes, before release.

We shall introduce a more generic input which can accomodate any number of additional arguments.

Apologies for the confusion, I was going to notify you, but you were quicker.

Anyway, many thanks for you contribution! :)

**Pull request merged**
